### ISSUE TITLE
Faltan notas para traductores

### ISSUE THREAD

**Issue by jmdaweb** [hxebolax/Add-on-packer#1]
Esto es una incidencia, también conocida como Issue. Las incidencias se usan para avisar de problemas o proponer mejoras. Se suelen redactar en inglés, pero en este caso creo que nos sentiremos mucho más cómodos en español.
El complemento necesita notas para traductores, de cara a que estos tengan claro para qué sirve cada cadena mientras la traducen con Poedit. Las cadenas para traductores se colocan en el código como si fueran comentarios, anteponiendo la almohadilla. Se sitúan justo encima de la línea que contiene la cadena traducible. Veamos un ejemplo en el fichero buildVars:
```
	# Translators: Summary for this add-on to be shown on installation and add-on information.
	"addon_summary": _("Add-on packer"),
```
Esta nota se agrega al fichero .pot cuando lo generas, y posteriormente a los .po que se crean a partir de él. En Poedit, la verás situándote sobre la cadena correspondiente con las flechas y navegando hacia la derecha con el navegador de objetos. Cada nota debe ser clara e indicar de forma inequívoca el propósito de la cadena a la que está asociada. Por ejemplo:
```
# Translators: label for the Close button in the add-on packager dialog
```

Ahora que tienes tu primera incidencia, puedes hacer varias cosas con ella:

* Responder desde el correo que te ha llegado. Cuidado con Thunderbird, las opciones Responder al remitente y Responder a la lista no eligen el mismo destinatario.
* Responder desde la página de la incidencia, utilizando el cuadro multilínea que encontrarás por abajo y pulsando el botón Comment al acabar.
* Cerrarla utilizando el botón Close. Esto se suele hacer si la incidencia no merece la pena o ya la has resuelto. Puedes cerrarla sin comentar nada o poniendo un comentario.

También podrías cerrarla directamente con un commit. Github interpreta algunas palabras de los mensajes del commit. Por ejemplo, podrías poner algo como esto en la consola:

```
git commit -m "Added strings for translators. Fixes #1"
```

Al hacer push, Github te cerrará la incidencia automáticamente. También puedes mencionar usuarios, como en Twitter, y hacer que se fijen en la incidencia y sus comentarios. Por ejemplo, @ivnc.

**Comment by hxebolax** [comment]
@jmdaweb solucionada incidencia. Añadidas todas las notas para traductores.
