### ISSUE TITLE
Preparación para la revisión de la comunidad internacional

### ISSUE THREAD

**Issue by jmdaweb** [hxebolax/Add-on-packer#5]
Ahora que @nvdaes ha actualizado la wiki de revisiones pendientes en la lista de complementos incluyendo este, aumentan las posibilidades de que alguien lo revise. Por ello, es importante pulir algunos aspectos de cara a que quede lo mejor posible, a pesar de que en la revisión básica no se suelen tener en cuenta o se expresan en forma de recomendaciones opcionales. Esto es lo que he encontrado en el código:

* Como el complemento sólo consta de un módulo, puedes llamarlo `addonPackager.py` y dejarlo directamente en la carpeta globalPlugins.
* Faltan notas para traductores en la línea 48. Podrías separar la llamada al decorador script en varias líneas, y meter las notas entre medias. Sería algo como esto:

```
	@script(gesture=None,
		# TRANSLATORS: nota para traductores sobre la descripción
		description= _("Show the plug-in packer window"),
		# TRANSLATORS: nota para traductores sobre la categoría
		category= _("Add-on packer"))
```

* En la línea 70 puedes optimizar la condición, reduciéndola de 4 líneas a 2 o incluso a una: `if not os.path.exists(self.directorySave): self.directorySave = ""`
* La línea 116 se puede eliminar.
* En la línea 135, el cuadro de edición es multilínea y de sólo lectura. Recuerdo que al quitar el flag multiline pasaba algo, pero no recuerdo qué. ¿Interesa que el usuario pueda escribir manualmente una ruta? En caso contrario, se podría mencionar en la documentación explicando por qué.
* Las líneas 197 y 198 se pueden quitar.
* Hay al menos dos nombres de variables en español: lista e hilo. Lista es relativamente fácil de entender en otros idiomas, pero hilo no.
* La documentación no está mal. Explica claramente el propósito del complemento, cómo usarlo, los atajos disponibles y qué riesgos conlleva. No obstante, le daría una vuelta con el corrector, especialmente a la traducción en español, y quizá sería adecuado reformular la que está en inglés.
* En cuanto a licencia y copyright, seguridad y experiencia de usuario no veo problemas. En este último punto has puesto mucho cuidado en anunciar al usuario los posibles errores que puedan afectarle, e ignorar aquellos que no tienen impacto, como el que se puede dar al guardar o recuperar la última ruta utilizada.

Tras este análisis, llego a la conclusión de que podrías corregir todo esto y liberar una nueva versión, pero no me parece estrictamente necesario o urgente.
¿Qué pensáis? CC: @javidominguez @sukiletxe @antramcs @ivnc @GerardKessler @peterrc87

**Comment by sukiletxe** [comment]
En la línea 70, a la condición reformulada le falta un not (if not os.path..exists...)

Por lo demás estoy de acuerdo y no encuentro nada más reseñable. Por cierto, dónde está esa wiki?

**Comment by jmdaweb** [comment]
Error de cálculo por escribir demasiado deprisa, supongo. Gracias!
La página de la wiki a la que hago referencia es esta: https://nvda-addons.groups.io/g/nvda-addons/wiki/27367

**Comment by javidominguez** [comment]
Hola. Si al cuadro de edición de solo lectura le quitas el flag multiline no recibirá el foco con tabulador.

￼

**Comment by hxebolax** [comment]
Gracias por vuestras sugerencias.

E aplicado todas las sugerencias y ya están subidas.

* Bien el cuadro de solo lectura del directorio esta puesto a si de manera informativa para que el usuario sepa que directorio a elegido o que directorio tiene guardado. Es de solo lectura por que prefiero que se elija desde su correspondiente ventana y no pueda ser modificado ya que tendríamos que contemplar más escenarios de errores.

En la documentación se avisa del cuadro de directorio, además e corregido unos fallos en la documentación en Español.

* Adicionalmente en el archivo addonPackager.py e agregado y agradecido a los traductores ya que veo innecesario tener que modificar todos los readme a estas alturas.

* En la línea 32 e agregado un comentario para que se sepa que IS_WIN_on es una bandera para saber cuando hay ventanas del complemento abiertas y no dejar que se ejecute una segunda instancia.

* En la línea 268 e agregado también un comentario para decir que la función zipfolder es para comprimir el directorio de complementos y quitar las carpetas __pycache__.

*E agregado el Chino simplificado a las traducciones

Quedo a expensas de cualquier cosa que veáis.

Muchas gracias.

**Comment by jmdaweb** [comment]
Pues yo creo que poco más se puede hacer. Vamos a darle unas horas a ver si alguien dice algo más, y cerramos.
